import { Form, usePage } from '@inertiajs/react';
import { ShieldCheck } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import Heading from '@/components/heading';
import TwoFactorRecoveryCodes from '@/components/two-factor-recovery-codes';
import TwoFactorSetupModal from '@/components/two-factor-setup-modal';
import { Button } from '@/components/ui/button';
import { useTwoFactorAuth } from '@/hooks/use-two-factor-auth';
import { disable, enable } from '@/routes/two-factor';

export type Props = {
    canManageTwoFactor?: boolean;
    requiresConfirmation?: boolean;
    twoFactorEnabled?: boolean;
};

type SharedProps = {
    store?: {
        theme?: 'default' | 'fashion_editorial';
    };
};

export default function ManageTwoFactor(props: Props) {
    const page = usePage();

    const sharedProps = page.props as unknown as SharedProps;

    const isFashionEditorial = sharedProps.store?.theme === 'fashion_editorial';

    const requiresConfirmation = props.requiresConfirmation ?? false;

    const twoFactorEnabled = props.twoFactorEnabled ?? false;

    const {
        qrCodeSvg,
        hasSetupData,
        manualSetupKey,
        clearSetupData,
        clearTwoFactorAuthData,
        fetchSetupData,
        recoveryCodesList,
        fetchRecoveryCodes,
        errors,
    } = useTwoFactorAuth();

    const [showSetupModal, setShowSetupModal] = useState<boolean>(false);

    const prevTwoFactorEnabled = useRef(twoFactorEnabled);

    useEffect(() => {
        if (prevTwoFactorEnabled.current && !twoFactorEnabled) {
            clearTwoFactorAuthData();
        }

        prevTwoFactorEnabled.current = twoFactorEnabled;
    }, [twoFactorEnabled, clearTwoFactorAuthData]);

    if (!(props.canManageTwoFactor ?? false)) {
        return null;
    }

    if (isFashionEditorial) {
        return (
            <div>
                <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
                    <div>
                        <p className="text-[9px] font-medium tracking-[0.16em] text-neutral-500 uppercase">
                            Two-factor authentication
                        </p>

                        <h2 className="mt-3 font-serif text-3xl leading-tight tracking-[-0.025em]">
                            Additional verification
                        </h2>
                    </div>

                    <div>
                        <p className="text-[9px] font-medium tracking-[0.14em] text-neutral-500 uppercase">
                            Status
                        </p>

                        <p className="mt-2 text-sm text-neutral-800">
                            {twoFactorEnabled ? 'Enabled' : 'Not enabled'}
                        </p>
                    </div>
                </div>

                <div className="mt-7 border-t border-neutral-300 pt-7">
                    {twoFactorEnabled ? (
                        <div>
                            <p className="max-w-2xl text-sm leading-7 text-neutral-600">
                                Two-factor authentication is active for your
                                account. When signing in, you will be asked for
                                a secure authentication code generated by the
                                authenticator application on your device.
                            </p>

                            <div className="mt-7">
                                <Form {...disable.form()}>
                                    {({ processing }) => (
                                        <button
                                            type="submit"
                                            disabled={processing}
                                            className="inline-flex min-h-11 items-center justify-center border border-red-700 px-6 text-[9px] font-medium tracking-[0.14em] text-red-700 uppercase transition hover:bg-red-700 hover:text-white disabled:cursor-not-allowed disabled:opacity-40"
                                        >
                                            {processing
                                                ? 'Disabling...'
                                                : 'Disable 2FA'}
                                        </button>
                                    )}
                                </Form>
                            </div>

                            <div className="mt-10 border-t border-neutral-300 pt-8">
                                <p className="mb-5 text-[9px] font-medium tracking-[0.16em] text-neutral-500 uppercase">
                                    Recovery access
                                </p>

                                <TwoFactorRecoveryCodes
                                    recoveryCodesList={recoveryCodesList}
                                    fetchRecoveryCodes={fetchRecoveryCodes}
                                    errors={errors}
                                />
                            </div>
                        </div>
                    ) : (
                        <div>
                            <p className="max-w-2xl text-sm leading-7 text-neutral-600">
                                Add another layer of protection to your account.
                                Once enabled, sign-in will require a secure code
                                from a TOTP-compatible authenticator application
                                in addition to your password.
                            </p>

                            <div className="mt-7">
                                {hasSetupData ? (
                                    <button
                                        type="button"
                                        onClick={() => setShowSetupModal(true)}
                                        className="inline-flex min-h-11 items-center justify-center border border-neutral-950 bg-neutral-950 px-6 text-[9px] font-medium tracking-[0.14em] text-white uppercase transition hover:bg-transparent hover:text-neutral-950"
                                    >
                                        Continue setup
                                    </button>
                                ) : (
                                    <Form
                                        {...enable.form()}
                                        onSuccess={() =>
                                            setShowSetupModal(true)
                                        }
                                    >
                                        {({ processing }) => (
                                            <button
                                                type="submit"
                                                disabled={processing}
                                                className="inline-flex min-h-11 items-center justify-center border border-neutral-950 bg-neutral-950 px-6 text-[9px] font-medium tracking-[0.14em] text-white uppercase transition hover:bg-transparent hover:text-neutral-950 disabled:cursor-not-allowed disabled:opacity-40"
                                            >
                                                {processing
                                                    ? 'Enabling...'
                                                    : 'Enable 2FA'}
                                            </button>
                                        )}
                                    </Form>
                                )}
                            </div>
                        </div>
                    )}
                </div>

                <TwoFactorSetupModal
                    isOpen={showSetupModal}
                    onClose={() => setShowSetupModal(false)}
                    requiresConfirmation={requiresConfirmation}
                    twoFactorEnabled={twoFactorEnabled}
                    qrCodeSvg={qrCodeSvg}
                    manualSetupKey={manualSetupKey}
                    clearSetupData={clearSetupData}
                    fetchSetupData={fetchSetupData}
                    errors={errors}
                />
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <Heading
                variant="small"
                title="Two-factor authentication"
                description="Manage your two-factor authentication settings"
            />

            {twoFactorEnabled ? (
                <div className="flex flex-col items-start justify-start space-y-4">
                    <p className="text-sm text-muted-foreground">
                        You will be prompted for a secure, random pin during
                        login, which you can retrieve from the TOTP-supported
                        application on your phone.
                    </p>

                    <div className="relative inline">
                        <Form {...disable.form()}>
                            {({ processing }) => (
                                <Button
                                    variant="destructive"
                                    type="submit"
                                    disabled={processing}
                                >
                                    Disable 2FA
                                </Button>
                            )}
                        </Form>
                    </div>

                    <TwoFactorRecoveryCodes
                        recoveryCodesList={recoveryCodesList}
                        fetchRecoveryCodes={fetchRecoveryCodes}
                        errors={errors}
                    />
                </div>
            ) : (
                <div className="flex flex-col items-start justify-start space-y-4">
                    <p className="text-sm text-muted-foreground">
                        When you enable two-factor authentication, you will be
                        prompted for a secure pin during login. This pin can be
                        retrieved from a TOTP-supported application on your
                        phone.
                    </p>

                    <div>
                        {hasSetupData ? (
                            <Button onClick={() => setShowSetupModal(true)}>
                                <ShieldCheck />
                                Continue setup
                            </Button>
                        ) : (
                            <Form
                                {...enable.form()}
                                onSuccess={() => setShowSetupModal(true)}
                            >
                                {({ processing }) => (
                                    <Button type="submit" disabled={processing}>
                                        Enable 2FA
                                    </Button>
                                )}
                            </Form>
                        )}
                    </div>
                </div>
            )}

            <TwoFactorSetupModal
                isOpen={showSetupModal}
                onClose={() => setShowSetupModal(false)}
                requiresConfirmation={requiresConfirmation}
                twoFactorEnabled={twoFactorEnabled}
                qrCodeSvg={qrCodeSvg}
                manualSetupKey={manualSetupKey}
                clearSetupData={clearSetupData}
                fetchSetupData={fetchSetupData}
                errors={errors}
            />
        </div>
    );
}
