import { Form, Head, setLayoutProps, usePage } from '@inertiajs/react';
import { REGEXP_ONLY_DIGITS } from 'input-otp';
import { useMemo, useState } from 'react';
import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
    InputOTP,
    InputOTPGroup,
    InputOTPSlot,
} from '@/components/ui/input-otp';
import { OTP_MAX_LENGTH } from '@/hooks/use-two-factor-auth';
import { store } from '@/routes/two-factor/login';

type SharedProps = {
    store?: {
        theme?: 'default' | 'fashion_editorial';
    };
};

export default function TwoFactorChallenge() {
    const page = usePage();

    const sharedProps = page.props as unknown as SharedProps;

    const isFashionEditorial = sharedProps.store?.theme === 'fashion_editorial';

    const [showRecoveryInput, setShowRecoveryInput] = useState<boolean>(false);

    const [code, setCode] = useState<string>('');

    const authConfigContent = useMemo<{
        title: string;
        description: string;
        toggleText: string;
    }>(() => {
        if (showRecoveryInput) {
            return {
                title: 'Recovery code',
                description:
                    'Please confirm access to your account by entering one of your emergency recovery codes.',
                toggleText: 'login using an authentication code',
            };
        }

        return {
            title: 'Authentication code',
            description:
                'Enter the authentication code provided by your authenticator application.',
            toggleText: 'login using a recovery code',
        };
    }, [showRecoveryInput]);

    setLayoutProps({
        title: authConfigContent.title,
        description: authConfigContent.description,
    });

    const toggleRecoveryMode = (clearErrors: () => void): void => {
        setShowRecoveryInput((current) => !current);
        clearErrors();
        setCode('');
    };

    if (isFashionEditorial) {
        return (
            <>
                <Head title="Two-factor authentication" />

                <div className="space-y-8">
                    <div className="border-b border-neutral-300 pb-7">
                        <p className="text-[9px] font-medium tracking-[0.16em] text-neutral-500 uppercase">
                            Account security
                        </p>

                        <h2 className="mt-3 font-serif text-3xl leading-tight font-normal tracking-[-0.025em] text-neutral-950">
                            {showRecoveryInput
                                ? 'Use a recovery code.'
                                : 'Verify your sign-in.'}
                        </h2>

                        <p className="mt-3 max-w-md text-sm leading-7 text-neutral-600">
                            {showRecoveryInput
                                ? 'Enter one of your emergency recovery codes to regain access to your account.'
                                : 'Enter the authentication code generated by your authenticator application.'}
                        </p>
                    </div>

                    <Form
                        {...store.form()}
                        className="space-y-7"
                        resetOnError
                        resetOnSuccess={!showRecoveryInput}
                    >
                        {({ errors, processing, clearErrors }) => (
                            <>
                                {showRecoveryInput ? (
                                    <div>
                                        <label
                                            htmlFor="recovery_code"
                                            className="text-[9px] font-medium tracking-[0.14em] text-neutral-500 uppercase"
                                        >
                                            Recovery code
                                        </label>

                                        <Input
                                            id="recovery_code"
                                            name="recovery_code"
                                            type="text"
                                            placeholder="Enter recovery code"
                                            autoComplete="one-time-code"
                                            autoFocus
                                            required
                                            className="mt-2 h-auto w-full rounded-none border-neutral-300 bg-transparent px-4 py-3 font-mono text-sm text-neutral-950 shadow-none placeholder:font-sans placeholder:text-neutral-400 focus-visible:border-neutral-950 focus-visible:ring-0"
                                        />

                                        <InputError
                                            className="mt-2"
                                            message={errors.recovery_code}
                                        />
                                    </div>
                                ) : (
                                    <div>
                                        <p className="text-center text-[9px] font-medium tracking-[0.14em] text-neutral-500 uppercase">
                                            Authentication code
                                        </p>

                                        <div className="mt-5 flex w-full items-center justify-center">
                                            <InputOTP
                                                name="code"
                                                maxLength={OTP_MAX_LENGTH}
                                                value={code}
                                                onChange={(value) =>
                                                    setCode(value)
                                                }
                                                disabled={processing}
                                                pattern={REGEXP_ONLY_DIGITS}
                                                autoFocus
                                            >
                                                <InputOTPGroup>
                                                    {Array.from(
                                                        {
                                                            length: OTP_MAX_LENGTH,
                                                        },
                                                        (_, index) => (
                                                            <InputOTPSlot
                                                                key={index}
                                                                index={index}
                                                                className="h-11 w-11 rounded-none border-neutral-300 bg-transparent text-base shadow-none first:rounded-none last:rounded-none"
                                                            />
                                                        ),
                                                    )}
                                                </InputOTPGroup>
                                            </InputOTP>
                                        </div>

                                        <div className="mt-3 text-center">
                                            <InputError message={errors.code} />
                                        </div>
                                    </div>
                                )}

                                <div className="border-t border-neutral-300 pt-6">
                                    <button
                                        type="submit"
                                        disabled={processing}
                                        className="inline-flex min-h-12 w-full items-center justify-center border border-neutral-950 bg-neutral-950 px-6 text-[9px] font-medium tracking-[0.14em] text-white uppercase transition hover:bg-transparent hover:text-neutral-950 disabled:cursor-not-allowed disabled:opacity-40"
                                    >
                                        {processing
                                            ? 'Verifying...'
                                            : 'Continue'}
                                    </button>
                                </div>

                                <div className="text-center text-sm leading-7 text-neutral-600">
                                    <span>
                                        {showRecoveryInput
                                            ? 'Have access to your authenticator? '
                                            : 'Cannot access your authenticator? '}
                                    </span>

                                    <button
                                        type="button"
                                        className="border-b border-neutral-950 pb-0.5 text-neutral-950 transition-opacity hover:opacity-60"
                                        onClick={() =>
                                            toggleRecoveryMode(clearErrors)
                                        }
                                    >
                                        {showRecoveryInput
                                            ? 'Use authentication code'
                                            : 'Use recovery code'}
                                    </button>
                                </div>
                            </>
                        )}
                    </Form>

                    <div className="border-t border-neutral-300 pt-6">
                        <p className="text-center text-xs leading-6 text-neutral-500">
                            This verification step helps protect your account
                            from unauthorized access.
                        </p>
                    </div>
                </div>
            </>
        );
    }

    return (
        <>
            <Head title="Two-factor authentication" />

            <div className="space-y-6">
                <Form
                    {...store.form()}
                    className="space-y-4"
                    resetOnError
                    resetOnSuccess={!showRecoveryInput}
                >
                    {({ errors, processing, clearErrors }) => (
                        <>
                            {showRecoveryInput ? (
                                <>
                                    <Input
                                        name="recovery_code"
                                        type="text"
                                        placeholder="Enter recovery code"
                                        autoFocus={showRecoveryInput}
                                        required
                                    />

                                    <InputError
                                        message={errors.recovery_code}
                                    />
                                </>
                            ) : (
                                <div className="flex flex-col items-center justify-center space-y-3 text-center">
                                    <div className="flex w-full items-center justify-center">
                                        <InputOTP
                                            name="code"
                                            maxLength={OTP_MAX_LENGTH}
                                            value={code}
                                            onChange={(value) => setCode(value)}
                                            disabled={processing}
                                            pattern={REGEXP_ONLY_DIGITS}
                                            autoFocus
                                        >
                                            <InputOTPGroup>
                                                {Array.from(
                                                    {
                                                        length: OTP_MAX_LENGTH,
                                                    },
                                                    (_, index) => (
                                                        <InputOTPSlot
                                                            key={index}
                                                            index={index}
                                                        />
                                                    ),
                                                )}
                                            </InputOTPGroup>
                                        </InputOTP>
                                    </div>

                                    <InputError message={errors.code} />
                                </div>
                            )}

                            <Button
                                type="submit"
                                className="w-full"
                                disabled={processing}
                            >
                                Continue
                            </Button>

                            <div className="text-center text-sm text-muted-foreground">
                                <span>or you can </span>

                                <button
                                    type="button"
                                    className="cursor-pointer text-foreground underline decoration-neutral-300 underline-offset-4 transition-colors duration-300 ease-out hover:decoration-current! dark:decoration-neutral-500"
                                    onClick={() =>
                                        toggleRecoveryMode(clearErrors)
                                    }
                                >
                                    {authConfigContent.toggleText}
                                </button>
                            </div>
                        </>
                    )}
                </Form>
            </div>
        </>
    );
}
